

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_schoolbag?serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ebag
    password: ebag
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

